name: "Set up system"
description: "Set up system"

inputs:
  python:
    description: "Python interpreter version"
    required: true

runs:
  using: "composite"
  steps:
    - name: Install Qt dependencies
      uses: tlambert03/setup-qt-libs@v1

    - name: Set up Python ${{ inputs.python }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python }}
